### ISSUE TITLE
Verify PracticeTask repo

### ISSUE THREAD

**Issue by szahedian** [szahedian/PracticeTask#15]
Verify that PracticeTask repo code satisfies requirements given in the [instructions](https://github.com/gslab-econ/admin/blob/master/practice-task/README.md).

**Comment by Houdanait** [comment]
Thanks a lot @szahedian

**Comment by Houdanait** [comment]
Hi @szahedian, the repository runs fine! All good by me. If you can summarise this issue and close it.

**Comment by szahedian** [comment]
**Summary:** Practice task repo was run and checked by returning RA (see above). The repo implements the changes required in the [Practice Task Instructions](https://github.com/gslab-econ/admin/blob/master/practice-task/README.md).
