### ISSUE TITLE
Fix stata script

### ISSUE THREAD

**Issue by szahedian** [szahedian/PracticeTask#4]
Need to edit `analysis/source/prepare_data/create_data.do` to successfully generate outputs.

**Comment by szahedian** [comment]
Note: I have to receive my STATA license and SIEPR laptop before beginning work on this issue.

**Comment by Houdanait** [comment]
@szahedian is there any update on the stata license?

**Comment by szahedian** [comment]
@Houdanait I was able to get a license for my personal machine through Dave Chan's lab. That's what I used for this issue.

I also got a license from the econ department, which I'll use on my SIEPR laptop.

**Comment by szahedian** [comment]
@Houdanait I'm also closing this issue, as it's addressed by #14.
